services:
  - type: web
    name: wotnot-backend
    env: docker
    plan: free   # or "starter" if free is not enough
    branch: main
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgres://<username>:<password>@<host>:5432/<dbname>
      - key: REDIS_URL
        value: redis://<host>:6379
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /docs
